version: '3.8'

services:
  webapi:
    image: webapi
    ports:
        - 8081:8081
    build:
      context: .
      dockerfile: WebApp/WebApp.Server/Dockerfile

  vueui:
    image: vueui
    build:
      context: .
      dockerfile: WebApp/webapp.client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webapi 