version: '3.8'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApp/WebApp.Server/Dockerfile
    ports:
      - "8080:80" 

  vueui:
    image: vueui
    build:
      context: .
      dockerfile: WebApp/webapp.client/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - webapi 